image: rust

before_script:
  - cargo version

stages:
  - check
  - test

check:
  stage: check
  script:
    - rustup component add clippy
    - cargo clippy --all --tests --all-features
  cache:
    paths:
      - target/
      - ~/.cargo/git
      - ~/.cargo/registry
  only:
    - tags
    - master

test:
  stage: test
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --all --all-features -o Html
  cache:
    paths:
      - target/
      - ~/.cargo/git
      - ~/.cargo/registry
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    paths:
      - tarpaulin-report.html
  only:
    - tags
    - master

cache:
  paths:
    - target/debug
