image: rust

before_script:
  - cargo version

stages:
  - check
  - test

check:
  script:
    - cargo clippy --all --tests --all-features
  only:
    - tags
    - master

test:
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --all --all-features
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    reports:
      cobertura:
        - cobertura.xml
  only:
    - tags
    - master

cache:
  paths:
    - target/debug
