image: rust

before_script:
  - cargo version

stages:
  - check
  - test

check:
  script:
    - cargo check --all --tests --all-features
  only:
    - tags
    - master

test:
  script:
    - cargo test --all --all-features
  only:
    - tags
    - master

cache:
  paths:
    - target/debug