image: rust

before_script:
  - cargo version

stages:
  - check
  - test

check:
  stage: check
  script:
    - rustup component add clippy
    - cargo clippy --all --tests --all-features
  cache:
    paths:
      - target/
  only:
    - tags
    - master

test:
  stage: test
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --all --all-features
  cache:
    paths:
      - target/
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    reports:
      cobertura:
        - cobertura.xml
  only:
    - tags
    - master

cache:
  paths:
    - target/debug
