[package]
name = "hsbf"
version = "0.1.0"
authors = ["Filippo Berto <berto.f@protonmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["md5_hash"]
md5_hash = ["md5"]
md4_hash = ["md4"]
metrics = []

[dependencies]
base64 = "0.10.1"
byteorder = "1.3.2"
itertools = "0.8.0"
log = "0.4.6"
md5 = {version = "0.6.1", optional = true}
md4 = {version = "0.8.0", optional = true}
num = "0.2.0"
rand = "0.7"
rayon = "1.2.0"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

[dev-dependencies]
env_logger = "0.7.0"
